print("Hello Insanos")
print("Suelten sus gaaa")
print("Nuetra mision y vision es inseminar minitas ufff")
print("Por lo que mejoraremos e implementaremos estraegias insanas")
print("Para ello necesitaremos dinero y personalidad")
print("Tenemos que enfocarnos en mejorar nuestros stats bases")
print("Aprender seduccion antes de la destruccion, this is cinema man")
print("Domarlas con elocuencia y violencia")